name: mobile_v2
description: Baby Talk vNext mobile boundary
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.11.4

dependencies:
  crypto: ^3.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fixtures/ritual_rooms/
    - assets/illustrations/rituals/
  uses-material-design: true
