create table if not exists analytics_events (
    id bigint generated by default as identity primary key,
    event_id varchar(128) not null,
    session_id varchar(64) not null,
    event_name varchar(64) not null,
    screen_name varchar(64),
    occurred_at timestamp not null,
    properties_json text not null,
    uploaded_at timestamp not null,
    constraint fk_analytics_events_session
        foreign key (session_id) references app_sessions (session_id),
    constraint uq_analytics_events_event_id
        unique (event_id)
);

create index if not exists idx_analytics_events_session_occurred_at
    on analytics_events (session_id, occurred_at);

create index if not exists idx_analytics_events_name_occurred_at
    on analytics_events (event_name, occurred_at);