create table if not exists households (
    household_id varchar(64) primary key,
    owner_account_id varchar(64) not null,
    status varchar(24) not null,
    created_at timestamp with time zone not null,
    revoked_at timestamp with time zone null,
    constraint fk_households_owner_account foreign key (owner_account_id) references accounts(account_id),
    constraint chk_households_status check (status in ('active', 'revoked'))
);

create table if not exists household_members (
    membership_id bigint generated by default as identity primary key,
    household_id varchar(64) not null,
    account_id varchar(64) not null,
    role varchar(32) not null,
    status varchar(24) not null,
    invited_by_account_id varchar(64) null,
    joined_at timestamp with time zone not null,
    last_accepted_at timestamp with time zone null,
    constraint fk_household_members_household foreign key (household_id) references households(household_id),
    constraint fk_household_members_account foreign key (account_id) references accounts(account_id),
    constraint fk_household_members_invited_by foreign key (invited_by_account_id) references accounts(account_id),
    constraint uq_household_members_account unique (account_id),
    constraint uq_household_members_household_account unique (household_id, account_id),
    constraint chk_household_members_role check (role in ('primary_caregiver', 'caregiver')),
    constraint chk_household_members_status check (status in ('active', 'revoked'))
);

create table if not exists caregiver_invites (
    invite_id bigint generated by default as identity primary key,
    token varchar(64) not null,
    household_id varchar(64) not null,
    inviter_account_id varchar(64) not null,
    target_role varchar(32) not null,
    source varchar(32) not null,
    status varchar(24) not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    accepted_at timestamp with time zone null,
    revoked_at timestamp with time zone null,
    accepted_by_account_id varchar(64) null,
    failure_reason varchar(128) null,
    constraint uq_caregiver_invites_token unique (token),
    constraint fk_caregiver_invites_household foreign key (household_id) references households(household_id),
    constraint fk_caregiver_invites_inviter foreign key (inviter_account_id) references accounts(account_id),
    constraint fk_caregiver_invites_accepted_by foreign key (accepted_by_account_id) references accounts(account_id),
    constraint chk_caregiver_invites_role check (target_role in ('primary_caregiver', 'caregiver')),
    constraint chk_caregiver_invites_status check (status in ('pending', 'accepted', 'revoked', 'expired'))
);

create table if not exists household_shared_context (
    household_id varchar(64) primary key,
    baby_profile_summary varchar(240) not null,
    continuity_summary varchar(240) not null,
    garden_summary varchar(240) not null,
    space_id varchar(64) not null,
    activity_id varchar(64) not null,
    latest_interaction_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_household_shared_context_household foreign key (household_id) references households(household_id)
);

create table if not exists caregiver_invite_events (
    event_id bigint generated by default as identity primary key,
    token varchar(64) null,
    household_id varchar(64) null,
    actor_account_id varchar(64) null,
    entrypoint varchar(24) not null,
    source varchar(32) null,
    requested_role varchar(32) null,
    platform varchar(16) null,
    result varchar(32) not null,
    failure_reason varchar(128) null,
    created_at timestamp with time zone not null,
    constraint fk_caregiver_invite_events_household foreign key (household_id) references households(household_id),
    constraint fk_caregiver_invite_events_actor foreign key (actor_account_id) references accounts(account_id),
    constraint chk_caregiver_invite_events_entrypoint check (
        entrypoint in ('create', 'accept', 'revoke', 'shared_context', 'landing', 'open_app', 'download')
    ),
    constraint chk_caregiver_invite_events_role check (
        requested_role is null or requested_role in ('primary_caregiver', 'caregiver')
    ),
    constraint chk_caregiver_invite_events_platform check (
        platform is null or platform in ('android', 'ios')
    ),
    constraint chk_caregiver_invite_events_result check (
        result in (
            'create',
            'page_view',
            'open_app_redirect',
            'download_fallback',
            'accept',
            'invalid',
            'expired',
            'already_used',
            'revoked',
            'role_not_allowed',
            'shared_context_unavailable'
        )
    )
);

create index if not exists idx_households_owner_status on households(owner_account_id, status);
create index if not exists idx_household_members_household_status on household_members(household_id, status, role);
create index if not exists idx_household_members_account_status on household_members(account_id, status);
create index if not exists idx_caregiver_invites_household_status on caregiver_invites(household_id, status, expires_at);
create index if not exists idx_caregiver_invites_inviter_created_at on caregiver_invites(inviter_account_id, created_at);
create index if not exists idx_household_shared_context_updated_at on household_shared_context(updated_at);
create index if not exists idx_caregiver_invite_events_token_created_at on caregiver_invite_events(token, created_at);
create index if not exists idx_caregiver_invite_events_household_result on caregiver_invite_events(household_id, result, created_at);
