create table if not exists accounts (
    account_id varchar(64) primary key,
    phone_number varchar(64) not null unique,
    status varchar(24) not null,
    latest_consent_status varchar(24) not null,
    created_at timestamp with time zone not null,
    deleted_at timestamp with time zone null,
    constraint chk_accounts_status check (status in ('active', 'deleted')),
    constraint chk_accounts_consent_status check (latest_consent_status in ('signed_out', 'accepted', 'revoked', 'deleted'))
);

create table if not exists account_sessions (
    session_id varchar(64) primary key,
    account_id varchar(64) not null,
    installation_id varchar(128) not null,
    status varchar(24) not null,
    created_at timestamp with time zone not null,
    revoked_at timestamp with time zone null,
    constraint fk_account_sessions_account foreign key (account_id) references accounts(account_id),
    constraint chk_account_sessions_status check (status in ('active', 'revoked', 'deleted'))
);

create table if not exists sms_challenges (
    challenge_id varchar(80) primary key,
    phone_number varchar(64) not null,
    verification_code varchar(16) not null,
    status varchar(24) not null,
    issued_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    verified_at timestamp with time zone null,
    failure_reason varchar(240) null,
    constraint chk_sms_challenges_status check (status in ('pending', 'verified', 'expired'))
);

create table if not exists consent_audit_logs (
    audit_id bigint generated by default as identity primary key,
    account_id varchar(64) not null,
    session_id varchar(64) not null,
    installation_id varchar(128) not null,
    action varchar(24) not null,
    result varchar(24) not null,
    reason varchar(240) null,
    created_at timestamp with time zone not null,
    constraint chk_consent_audit_action check (action in ('accept', 'revoke', 'delete')),
    constraint chk_consent_audit_result check (result in ('applied', 'duplicate'))
);

create table if not exists interaction_events (
    event_key varchar(128) primary key,
    account_id varchar(64) not null,
    session_id varchar(64) not null,
    installation_id varchar(128) not null,
    local_event_id varchar(96) not null,
    space_id varchar(96) not null,
    activity_id varchar(96) not null,
    phrase_id varchar(120) not null,
    reaction_type varchar(32) not null,
    client_timestamp timestamp with time zone not null,
    received_at timestamp with time zone not null,
    constraint fk_interaction_events_account foreign key (account_id) references accounts(account_id),
    constraint fk_interaction_events_session foreign key (session_id) references account_sessions(session_id),
    constraint chk_interaction_events_reaction_type check (reaction_type in ('calm', 'engaged', 'imitated', 'needs_break'))
);

create index if not exists idx_account_sessions_account_status on account_sessions(account_id, status);
create index if not exists idx_consent_audit_logs_account_created_at on consent_audit_logs(account_id, created_at);
create index if not exists idx_interaction_events_account_installation_time on interaction_events(account_id, installation_id, client_timestamp);
create index if not exists idx_sms_challenges_phone_status on sms_challenges(phone_number, status);
