create table if not exists mentor_turns (
    turn_id varchar(80) primary key,
    correlation_id varchar(96) not null,
    installation_id varchar(128) not null,
    session_id_hint varchar(128) null,
    account_id_hint varchar(128) null,
    surface varchar(32) not null,
    mode varchar(32) not null,
    result varchar(24) not null,
    phase varchar(64) not null,
    request_summary varchar(240) not null,
    response_summary varchar(240) not null,
    response_text varchar(800) not null,
    provider_mode varchar(32) not null,
    blocked_fallback boolean not null,
    retryable boolean not null,
    created_at timestamp with time zone not null,
    constraint chk_mentor_turns_result check (result in ('success', 'fallback'))
);

create table if not exists mentor_audit_logs (
    audit_id bigint generated by default as identity primary key,
    correlation_id varchar(96) not null,
    installation_id varchar(128) not null,
    session_id_hint varchar(128) null,
    account_id_hint varchar(128) null,
    event_type varchar(64) not null,
    phase varchar(64) not null,
    result varchar(24) not null,
    request_summary varchar(240) null,
    response_summary varchar(240) null,
    reason varchar(240) null,
    failure_code varchar(64) null,
    retryable boolean not null,
    rate_limited boolean not null,
    created_at timestamp with time zone not null,
    constraint chk_mentor_audit_logs_result check (result in ('accepted', 'success', 'fallback', 'error', 'rejected'))
);

create index if not exists idx_mentor_turns_installation_created_at
    on mentor_turns(installation_id, created_at);
create index if not exists idx_mentor_turns_correlation_id
    on mentor_turns(correlation_id);
create index if not exists idx_mentor_audit_logs_installation_created_at
    on mentor_audit_logs(installation_id, created_at);
create index if not exists idx_mentor_audit_logs_correlation_id
    on mentor_audit_logs(correlation_id, created_at);
create index if not exists idx_mentor_audit_logs_request_window
    on mentor_audit_logs(installation_id, event_type, created_at);
