create table if not exists release_distribution_events (
    event_id bigint generated by default as identity primary key,
    entrypoint varchar(16) not null,
    release_channel varchar(32) not null,
    source varchar(32) not null,
    platform varchar(16) null,
    result varchar(32) not null,
    failure_reason varchar(128) null,
    created_at timestamp with time zone not null,
    constraint chk_release_distribution_entrypoint check (entrypoint in ('download', 'upgrade')),
    constraint chk_release_distribution_result check (
        result in ('page_view', 'redirect', 'unavailable', 'invalid_channel', 'invalid_source', 'invalid_platform')
    )
);

create index if not exists idx_release_distribution_events_channel_source_result
    on release_distribution_events(release_channel, source, result, created_at);
create index if not exists idx_release_distribution_events_platform_result
    on release_distribution_events(platform, result, created_at);
create index if not exists idx_release_distribution_events_created_at
    on release_distribution_events(created_at);
