create table if not exists share_landing_cards (
    share_id bigint generated by default as identity primary key,
    token varchar(64) not null,
    source varchar(32) not null,
    headline varchar(80) not null,
    story_text varchar(280) not null,
    phrase_text varchar(120) null,
    phrase_translation varchar(120) null,
    recommendation_title varchar(120) null,
    recommendation_reason varchar(160) null,
    space_id varchar(64) null,
    activity_id varchar(64) null,
    platform_hint varchar(16) null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    constraint uq_share_landing_cards_token unique (token),
    constraint chk_share_landing_source check (
        source in ('latest_impact', 'continuity_recommendation', 'paired_progress')
    ),
    constraint chk_share_landing_platform_hint check (
        platform_hint is null or platform_hint in ('android', 'ios')
    )
);

create index if not exists idx_share_landing_cards_expires_at
    on share_landing_cards(expires_at, created_at);
create index if not exists idx_share_landing_cards_source_created_at
    on share_landing_cards(source, created_at);

create table if not exists share_landing_events (
    event_id bigint generated by default as identity primary key,
    token varchar(64) not null,
    source varchar(32) null,
    entrypoint varchar(24) not null,
    platform varchar(16) null,
    result varchar(32) not null,
    failure_reason varchar(128) null,
    created_at timestamp with time zone not null,
    constraint chk_share_landing_event_entrypoint check (
        entrypoint in ('create', 'landing', 'open_app', 'download')
    ),
    constraint chk_share_landing_event_result check (
        result in ('create', 'page_view', 'open_app_redirect', 'download_fallback', 'invalid', 'expired', 'unavailable')
    ),
    constraint chk_share_landing_event_platform check (
        platform is null or platform in ('android', 'ios')
    )
);

create index if not exists idx_share_landing_events_token_result
    on share_landing_events(token, result, created_at);
create index if not exists idx_share_landing_events_source_platform_result
    on share_landing_events(source, platform, result, created_at);
create index if not exists idx_share_landing_events_created_at
    on share_landing_events(created_at);
