import 'dart:typed_data';

import 'package:audioplayers/audioplayers.dart';
import 'package:mobile/features/care_path/domain/models/care_path_models.dart';
import 'package:mobile/features/care_path/data/audio/generated_audio_repository.dart';
import 'package:mobile/features/practice/presentation/practice_audio_controller.dart';

abstract interface class CareAudioPlaybackController {
  Stream<void> get completionStream;

  Future<void> play(CareAudioSource source);

  Future<void> stop();

  Future<void> dispose();
}

class SourceNeutralCareAudioPlaybackController
    implements CareAudioPlaybackController {
  SourceNeutralCareAudioPlaybackController({
    required GeneratedAudioRepository generatedAudioRepository,
    CareAudioOutput? output,
  }) : _generatedAudioRepository = generatedAudioRepository,
       _output = output ?? AudioplayersCareAudioOutput();

  final GeneratedAudioRepository _generatedAudioRepository;
  final CareAudioOutput _output;
  int _intent = 0;

  @override
  Stream<void> get completionStream => _output.completionStream;

  @override
  Future<void> play(CareAudioSource source) async {
    final intent = ++_intent;
    switch (source) {
      case CareAssetAudioSource(:final assetPath):
        await _output.playAsset(_normalizedAssetPath(assetPath));
      case GeneratedCareAudioSource():
        final payload = await _generatedAudioRepository.load(source);
        if (intent != _intent) {
          return;
        }
        await _output.playBytes(payload.bytes, payload.mimeType);
    }
  }

  @override
  Future<void> stop() async {
    _intent += 1;
    await _output.stop();
  }

  @override
  Future<void> dispose() async {
    _intent += 1;
    await _output.dispose();
  }

  String _normalizedAssetPath(String path) {
    final normalized = path.trim();
    if (normalized.isEmpty) {
      throw ArgumentError.value(path, 'path', '音频资源缺失。');
    }
    return normalized.startsWith('assets/')
        ? normalized.substring(7)
        : normalized;
  }
}

abstract interface class CareAudioOutput {
  Stream<void> get completionStream;

  Future<void> playAsset(String assetPath);

  Future<void> playBytes(List<int> bytes, String mimeType);

  Future<void> stop();

  Future<void> dispose();
}

class AudioplayersCareAudioOutput implements CareAudioOutput {
  AudioplayersCareAudioOutput({AudioPlayer? player})
    : _player = player ?? AudioPlayer();

  final AudioPlayer _player;

  @override
  Stream<void> get completionStream => _player.onPlayerComplete;

  @override
  Future<void> playAsset(String assetPath) {
    return _player.play(AssetSource(assetPath));
  }

  @override
  Future<void> playBytes(List<int> bytes, String mimeType) {
    return _player.play(
      BytesSource(Uint8List.fromList(bytes), mimeType: mimeType),
    );
  }

  @override
  Future<void> stop() => _player.stop();

  @override
  Future<void> dispose() => _player.dispose();
}

/// Compatibility adapter for existing test and legacy factories. It never
/// converts generated bytes into files and deliberately rejects them.
class LegacyPracticeCareAudioPlaybackController
    implements CareAudioPlaybackController {
  LegacyPracticeCareAudioPlaybackController(this._delegate);

  final PracticeAudioController _delegate;

  @override
  Stream<void> get completionStream => _delegate.completionStream;

  @override
  Future<void> play(CareAudioSource source) {
    if (source case CareAssetAudioSource(:final assetPath)) {
      final normalized = assetPath.startsWith('assets/')
          ? assetPath.substring(7)
          : assetPath;
      return _delegate.playAsset(normalized);
    }
    throw UnsupportedError('生成音频控制器不可用。');
  }

  @override
  Future<void> stop() => _delegate.stop();

  @override
  Future<void> dispose() => _delegate.dispose();
}
