postgres:
  image:
    repository: pgvector/pgvector
    tag: pg17
  auth:
    database: babytalk
    username: babytalk
    password: babytalk
  primary:
    resources: {}

redis:
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0
    persistence:
      enabled: false

minio:
  auth:
    rootUser: babytalk
    rootPassword: babytalk123
  defaultBuckets: babytalk
  persistence:
    enabled: false
  mode: standalone
