apiVersion: v1
kind: Service
metadata:
  name: {{ include "babytalk.componentFullname" (dict "root" . "component" "app-api") }}
  labels:
    {{- include "babytalk.componentLabels" (dict "root" . "component" "app-api") | nindent 4 }}
spec:
  type: {{ .Values.appApi.service.type }}
  ports:
    - name: http
      port: {{ .Values.appApi.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "babytalk.componentSelectorLabels" (dict "root" . "component" "app-api") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "babytalk.componentFullname" (dict "root" . "component" "admin-api") }}
  labels:
    {{- include "babytalk.componentLabels" (dict "root" . "component" "admin-api") | nindent 4 }}
spec:
  type: {{ .Values.adminApi.service.type }}
  ports:
    - name: http
      port: {{ .Values.adminApi.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "babytalk.componentSelectorLabels" (dict "root" . "component" "admin-api") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "babytalk.componentFullname" (dict "root" . "component" "admin-web") }}
  labels:
    {{- include "babytalk.componentLabels" (dict "root" . "component" "admin-web") | nindent 4 }}
spec:
  type: {{ .Values.adminWeb.service.type }}
  ports:
    - name: http
      port: {{ .Values.adminWeb.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "babytalk.componentSelectorLabels" (dict "root" . "component" "admin-web") | nindent 4 }}
